# Generated by Django 4.0.4 on 2022-04-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_business_description_profile_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
