# Generated by Django 4.0.4 on 2022-04-17 18:41

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_number',
            field=phone_field.models.PhoneField(blank=True, help_text="Enter your Business' Phone Number", max_length=31),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
