# Generated by Django 4.0.4 on 2022-04-18 11:15

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_business_business_number_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='location',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_number',
            field=phone_field.models.PhoneField(blank=True, help_text="Enter your Business' Phone Number, ext(extention) is optional", max_length=31),
        ),
    ]
