# Generated by Django 4.0.4 on 2022-04-19 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='users_neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='base.neighbourhood'),
        ),
    ]
